### ISSUE TITLE
I can't format partitions

### ISSUE THREAD

**Issue by ghost** [CarbonROM/android_device_motorola_cedric#1]
Hi, I briefly used this ROM but when I want to install another I have problems.

I can't format Data or other partitions, can you help me, please?
Or at least give me an idea.

In TWRP I can't format the partitions either.

![134724674_420501749099084_3801563338271367091_n](https://user-images.githubusercontent.com/75474872/103433263-6677e380-4bbc-11eb-8047-8baadabe7001.png)

**Comment by Dislekzi4** [comment]
Please reply.
